-- CreateTable
CREATE TABLE "public"."scraped_data" (
    "id" TEXT NOT NULL,
    "appId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "content" TEXT,
    "url" TEXT NOT NULL,
    "metaTags" JSONB,
    "openGraphData" JSONB,
    "twitterCardData" JSONB,
    "jsonLdData" JSONB,
    "headings" TEXT[],
    "paragraphs" TEXT[],
    "lists" TEXT[],
    "features" TEXT[],
    "benefits" TEXT[],
    "pricing" TEXT[],
    "testimonials" TEXT[],
    "images" JSONB,
    "videos" TEXT[],
    "documents" TEXT[],
    "logoUrl" TEXT,
    "favicon" TEXT,
    "socialLinks" JSONB,
    "contactInfo" JSONB,
    "technologies" TEXT[],
    "performanceMetrics" JSONB,
    "seoScore" DOUBLE PRECISION,
    "mobileOptimized" BOOLEAN NOT NULL DEFAULT false,
    "httpsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "wordCount" INTEGER,
    "readingTime" INTEGER,
    "languageDetected" TEXT,
    "keywords" TEXT[],
    "sentiment" TEXT,
    "companyInfo" JSONB,
    "businessModel" TEXT,
    "industryCategory" TEXT,
    "navigationMenu" TEXT[],
    "footerLinks" TEXT[],
    "internalLinks" TEXT[],
    "externalLinks" TEXT[],
    "products" JSONB,
    "categories" TEXT[],
    "paymentMethods" TEXT[],
    "shippingInfo" TEXT,
    "analyticsTools" TEXT[],
    "trackingPixels" TEXT[],
    "scrapeQuality" DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    "completeness" DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    "lastScrapedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "scrapeDuration" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "scraped_data_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "scraped_data_appId_key" ON "public"."scraped_data"("appId");

-- AddForeignKey
ALTER TABLE "public"."scraped_data" ADD CONSTRAINT "scraped_data_appId_fkey" FOREIGN KEY ("appId") REFERENCES "public"."apps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
